name: WakaTime Readme

on:
  schedule:
    - cron: '0 0 * * *' # update setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "False"
          SHOW_PROJECTS: "True"
          SHOW_OS: "False"
          SHOW_COMMIT: "False"
