name: WakaTime Readme

on:
  schedule:
    - cron: '0 0 * * *'  # update setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
